# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
 [line_break]
 disabled = false

# Replace the "❯" symbol in the prompt with "➜"
 [character]                         # The name of the module we are configuring is "character"
 success_symbol = "[󰘧 ](bold green)"
 error_symbol = "[ ](bold red)"

 [cmd_duration]
 min_time = 500
 format = " [󰔟 $duration ](bold cyan)"
# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """
#
# Disable the package module, hiding it from the prompt completely
 [package]
 disabled = false

 [battery]
 full_symbol = ""
 charging_symbol = ""
 discharging_symbol = ""
 format = "[$symbol $percentage ]($style)"
 disabled = true

 [[battery.display]]
 threshold = 30
 style = "bold red"
 
 [[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
 threshold = 45
 style = "bold yellow"

 [username]
 style_user = "white bold"
 style_root = "black bold"
 format = " [$user]($style) "
 disabled = false
 show_always = true

 [directory]
 truncation_length = 8
 truncation_symbol = ""
 format = "[  $path]($style)[$read_only]($read_only_style) "
 home_symbol = "~"
 style = "bold purple"

 [git_branch]
 style = "bold #eb6c8c"

 [git_status]
 conflicted = " "
 ahead = ""
 behind = ""
 diverged = ""
 untracked = ""
 stashed = " "
 modified = " "
 staged = '[ \($count\)](green)'
 renamed = " "
 deleted = " "
 style = "bold #62f0a0"

